### ISSUE TITLE
Support for new bing chat.

### ISSUE THREAD

**Issue by sam1am** [lucalewin/better-bing#1]
Love it, but looking for something that supports the new bing chat. Any plans?

**Comment by lucalewin** [comment]
Thanks for using my Bing dark mode extension! I'm currently working on adding support for Bing Chat, but it's my first extension and there are a few challenges with the shadowRoots. I'll post an update if I find a solution.

**Comment by sam1am** [comment]
Thanks. Congrats on your first extension. May Bing guide you in your quest. Amen.
