### ISSUE TITLE
bing chat

### ISSUE THREAD

**Issue by LiaMsiTi** [lucalewin/better-bing#4]
On bing chat the respond text is black on a grey background so it's hard to read.

**Comment by lucalewin** [comment]
Seems like Microsoft changed something again...
I'll fix it

**Comment by lucalewin** [comment]
This might actually take a while.

They added some extra styling to the container of the text.
Normally this would be quite easy to fix with an injected stylesheet, but they are using a lot of shadow roots which do not inherit the global styling. 
I solved it by injecting a ˋstyleˋ element into the shadow root.
This did not work here and I don't know why.
I'll have to try out a few things but that could take a couple of days

**Comment by LiaMsiTi** [comment]
They keep changing things making it harder for you, they should have a dark mode in their service in the first place.
I really appreciate your effort. 
Take your time.

**Comment by lucalewin** [comment]
I think I found a solution. The problem was that the text generation was animated and every time a new letter was added they also added their stylesheet again. The extension now listens for a change in the message and injects the stylesheet again too.
